### ISSUE TITLE
Rsync with SSH keeps asking for password

### ISSUE THREAD

**Issue by louisdj** [axiom-data-science/rsync-server#1]
Hi

I configured the docker container as said, and added an authorized_keys file with the publick key of my computer, but when I try to execute the rsync command or just do an SSH it keeps asking for a password instead of using the key...

**Comment by kwilcox** [comment]
Can you post your `docker run` command?

**Comment by louisdj** [comment]
```
   docker run -d --name=rsync \
       --restart unless-stopped \
       -v /volume1/intprdjava01_backup:/sqldump \
       -v /volume1/docker/Javadoc:/javadoc \
       -e USERNAME=admin \
       -e PASSWORD=mysecret \
       -e VOLUME=/myvolume \
       -v /volume1/intprdjava01_backup/ssh-vol:/root/.ssh/ \
       -p 9000:22 \
       axiom/rsync-server
```

**Comment by kwilcox** [comment]
Are you mounting `/volume1/intprdjava01_backup` twice on purpose? Once to `/sqldump` and then the subdirectory `ssh-vol` to `/root/.ssh`? Seems funky. You could make the later read-only with `:ro` and it would feel less funky to me. :shrug:

What is the contents of `/volume1/intprdjava01_backup/ssh-vol`?  This works for me if I have a folder called `authorized_keys` inside of it that has the correct permissions (`0600`).

**Comment by louisdj** [comment]
Hi

The issue is fixed; there was something wrong with the authorized_keys file, where an 's' was missing in 'ssh' at the begin of a key...
