### ISSUE TITLE
Version for arm 64

### ISSUE THREAD

**Issue by alessandro-massarenti** [axiom-data-science/rsync-server#12]
are you going to publish an arm64 image for this container?

**Comment by gamegine** [comment]
you can build it, the base image is compatible arm
https://github.com/docker-library/repo-info/blob/master/repos/debian/remote/bullseye-slim.md

**Comment by YinhaoHe** [comment]
I opened an issue and found there was a similar request, so I just build one here is the link: https://hub.docker.com/r/looooooper/rsync-server

Kudos to the code author, I only just build it and supported multi platforms.
