### ISSUE TITLE
Has the project been abandoned ??

### ISSUE THREAD

**Issue by gamegine** [axiom-data-science/rsync-server#17]
Hello,
I haven't seen any changes since November
my pull request has been pending since.
Was the project abandoned?

**Comment by srstsavage** [comment]
The primary maintainer for the project has moved on and we don't use the project extensively, so resources for maintenance are unfortunately limited. Contributions are still appreciated and I intend to periodically review and merge them. That said, if a more active, community supported fork evolved I would happily point others to it in the README!
