### ISSUE TITLE
docker容器创建一段时间后报错

### ISSUE THREAD

**Issue by appleftg** [axiom-data-science/rsync-server#3]
请教一下，最近docker容器报错，重新创建容器后正常，过一段时间后又是同样的错误，有什么解决办法呢？

创建容器命令：
 docker run -d \
    --name rsync-server  \
    -p 873:873 \
    -v /home/ft/docker/sync:/data \
    -e USERNAME=apple \
    -e PASSWORD=root \
    -e VOLUME=/data \
    -e ALLOW=192.168.11.0/24 \
    --restart=unless-stopped \
    apnar/rsync-server

错误日志：
failed to create pid file /var/run/rsyncd.pid: File exists
2020/11/19 13:15:42 [1] rsync: failed to create pid file /var/run/rsyncd.pid: File exists (17)
2020/11/19 13:15:42 [1] rsync error: error in file IO (code 11) at clientserver.c(1113) [Receiver=3.1.2]

**Comment by kwilcox** [comment]
```shell
$ docker run --rm --name rsync-server -p 873:873 -v /home/ft/docker/sync:/data -e USERNAME=apple -e PASSWORD=root -e VOLUME=/data -e ALLOW=192.168.11.0/24 axiom/rsync-server
2020/11/23 21:20:05 [1] rsyncd version 3.1.3 starting, listening on port 873
```

**Comment by appleftg** [comment]
> ```shell
> $ docker run --rm --name rsync-server -p 873:873 -v /home/ft/docker/sync:/data -e USERNAME=apple -e PASSWORD=root -e VOLUME=/data -e ALLOW=192.168.11.0/24 axiom/rsync-server
> 2020/11/23 21:20:05 [1] rsyncd version 3.1.3 starting, listening on port 873
> ```

好的，回去试试，谢谢
