### ISSUE TITLE
Remove the chmod and chown for authorized_keys

### ISSUE THREAD

**Issue by romulus-ai** [axiom-data-science/rsync-server#4]
This small step, prevents usage of configmaps for authorized_keys in K8S.

**Comment by Brawn1** [comment]
Hy,

the chmod and chown is added, to work out of the box with Clusterfilesystem PVC.
So the user can send self with ssh-copy-id her public key.

without chmod and chown, the authorized_keys is not working.

i think the solution is, detect if permissions is correct, or if authorized_keys exists on Container creating.

**Comment by Brawn1** [comment]
OK, i see the loop, and check this issue. :-)

**Comment by kwilcox** [comment]
@romulus-ai Would you imagine this being controlled by an environmental variable that would disable the `authorized_keys` file mods, or checking if file existed and already have the correct ownership and permissions before modding? If you had a yaml laying around of how you typically mount authorized_keys using ConfigMaps I would be willing to test it with minikube.

**Comment by romulus-ai** [comment]
Think the better approach is to check the correct permissions before changing them and to fail if the permissions are wrong and cannot be changed.

**Comment by srstsavage** [comment]
Potential fix here, reviews/comments welcome.

https://github.com/axiom-data-science/rsync-server/pull/22
