### ISSUE TITLE
Rsync.pid failed to create after OS reboot

### ISSUE THREAD

**Issue by Quentintin** [axiom-data-science/rsync-server#8]
Hello, 😃 

I ran this container without any problems through Docker Desktop on Windows 10 (with WSL2) : 
`docker run --restart unless-stopped --name=rsync_server ...`

but when I reboot my computer, I get this error and container wont run:
```
2021/07/08 13:00:25 [1] rsync error: error in file IO (code 11) at clientserver.c(1154) [Receiver=3.1.3]
2021/07/08 13:01:25 [1] rsync: failed to create pid file /var/run/rsyncd.pid: File exists (17)
```

No trouble when I restart Docker properly (Right click on item systray > Restart Docker)

Do you know this issue ? Do you have any solution for this ? 
Thank you :)

**Comment by lbesnard** [comment]
I have the same issue!

**Comment by Quentintin** [comment]
I wrote fix on forked repo : https://github.com/Quentintin/rsync-server

It works for me !
